### ISSUE TITLE
snap fails on focal and jammy VMs and containers

### ISSUE THREAD

**Issue by nicolasbock** [canonical/hotsos#625] opened 2023-05-30 20:43 UTC
Running the `hotsos` snap on either Focal or Jammy VMs (`lxc launch images:ubuntu/focal`) fails with:

```console
ubuntu@stirring-barnacle:~$ hotsos
Traceback (most recent call last):
  File "/snap/hotsos/737/bin/hotsos", line 5, in <module>
    from hotsos.cli import main
  File "/snap/hotsos/737/lib/python3.8/site-packages/hotsos/cli.py", line 14, in <module>
    from hotsos.core.host_helpers import CLIHelper
  File "/snap/hotsos/737/lib/python3.8/site-packages/hotsos/core/host_helpers/__init__.py", line 1, in <module>
    from .cli import CLIHelper  # noqa: F403,F401
  File "/snap/hotsos/737/lib/python3.8/site-packages/hotsos/core/host_helpers/cli.py", line 12, in <module>
    from hotsos.core.host_helpers.common import HostHelpersBase
  File "/snap/hotsos/737/lib/python3.8/site-packages/hotsos/core/host_helpers/common.py", line 4, in <module>
    from searchkit.utils import MPCache
  File "/snap/hotsos/737/lib/python3.8/site-packages/searchkit/utils.py", line 6, in <module>
    import _gdbm
ModuleNotFoundError: No module named '_gdbm'
```

It might be time to completely retire snaps 😢

**Comment by nicolasbock** [comment] 2023-05-30 20:47
Interestingly, the snap works from the `ubuntu` remote, i.e. when `lxc launch ubuntu:focal`.

**Comment by dosaboy** [comment] 2023-05-31 08:13
@nicolasbock i think that is something to do with the type of image used to create the container rather than the snap itself. If i use your first method, snapd is not even installed in the image but if try the usual approach of ubuntu:<series> it works:

```
ubuntu@dev:~$ lxc launch images:ubuntu/focal
Creating the instance
Instance name is: communal-polecat          
Starting communal-polecat
ubuntu@dev:~$ lxc exec communal-polecat bash
root@communal-polecat:~# snap install hotsos --classic
bash: snap: command not found
root@communal-polecat:~# exit
Error: Command not found
ubuntu@dev:~$ lxc launch ubuntu/focal
Creating the instance
The local image 'ubuntu/focal' couldn't be found, trying 'ubuntu:focal' instead.
Instance name is: large-piglet            
Starting large-piglet
ubuntu@dev:~$ lxc exec large-piglet bash
root@large-piglet:~# snap install hotsos --classic
hotsos 1.1.14.post16 from Edward Hope-Morley (hopem) installed
root@large-piglet:~# hotsos
INFO: analysing localhost -
hotsos:
  version: '737'
  repo-info: ef471b16
system:
  hostname: large-piglet
  os: ubuntu focal
  num-cpus: 8
  load: 0.85, 0.65, 0.38
  virtualisation: lxc
  rootfs: /dev/mapper/vgubuntu-root 957062368 566508540 341864064  63% /
  unattended-upgrades: ENABLED
  date: Wed May 31 08:11:06 UTC 2023
  ubuntu-pro:
    status: not-attached
  potential-issues:
    SystemWarnings:
      - Unattended upgrades are enabled which can lead to uncontrolled changes to
        this environment. If maintenance windows are required please consider disabling
        unattended upgrades. (origin=system.auto_scenario_check)
lxd:
  services:
    systemd:
      enabled:
        - lxd-agent
        - lxd-agent-9p
        - snap.lxd.activate
      static:
        - snap.lxd.daemon
      transient:
        - snap.lxd.workaround
    ps: []
  snaps:
    - lxd 4.0.9-a29c6f1
  dpkg:
    lxd-agent-loader: '0.4'
kernel:
  version: 5.19.0-42-generic
  boot: ro quiet splash vt.handoff=7
  cpu:
    vendor: genuineintel
    model: intel(r) core(tm) i7-7700k
    smt: enabled
    cpufreq-scaling-governor: performance
```

**Comment by dosaboy** [comment] 2023-05-31 08:32
so the issue is not the snap but the image used to create container. if you use ubuntu@focal it works just fine. ill close the issue since it doesn't seem to be a problem with the snap but please re-open if we need to look further.

**Closed by dosaboy** 2023-05-31 08:32 UTC

**Comment by nicolasbock** [comment] 2023-05-31 12:21
Thanks for digging into this further. I agree, let's close this issue.
